Update and enhancement the command line
stevebauman/autodoc-facades pull request #2
Opened 2024-01-12 15:23 UTC by michaelnabil230

This PR is for removing the `spatie/php-structure-discoverer` and using the `Finder` from `Symfony`

2024-01-15 20:58 UTC, stevebauman commented
Thanks for the PR! Tests are failing 👍

2024-01-16 00:12 UTC, michaelnabil230 commented
Hi @stevebauman, I fixed the issue and you can run the workflow again

2024-01-16 00:18 UTC, stevebauman requested changes

2024-01-16 00:18 UTC, stevebauman commented on README.md
> +php artisan autodoc:facades {path} {--only=} {--except=}
This is a breaking change, arg needs to remain `paths`.

2024-01-16 00:18 UTC, stevebauman commented on README.md
> +> All path you provide that do not start with a directory separator will use the commands current working directory as the base path.
Please revert these `path` find and replace changes 👍

2024-01-16 00:18 UTC, stevebauman commented on src/Commands/DocumentFacades.php
> +        return collect(Finder::create()->files()->depth(0)->in($this->argument('path'))->name('*.php'))
This needs to support searching multiple paths, like was previously supported with Spatie Structure Discovery 👍

2024-01-17 15:32 UTC, stevebauman approved these changes

2024-01-17 15:32 UTC, merged

2024-01-17 15:33 UTC, stevebauman commented
Thanks @michaelnabil230! Really appreciate your contribution! 🙏